crm_facturation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from scaffolding.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("scaffolding.urls")),
    #path("", include("django.contrib.auth.urls")),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    ]

scaffolding/urls.py
from django.urls import path
from . import views
from scaffolding.views import *

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path('customer/', CustomerListView.as_view()),
    path('customer/<int:pk>/', CustomerDetailView.as_view()),
    path('customer/create/', CustomerCreateView.as_view()),
    path('customer/<int:pk>/update/', CustomerUpdateView.as_view()),
    path('customer/<int:pk>/delete/', CustomerDeleteView.as_view()),
    
    path('category/', CategoryListView.as_view()),
    path('category/<int:pk>/', CategoryDetailView.as_view()),
    path('category/create/', CategoryCreateView.as_view()),
    path('article/', ArticleCreateView.as_view()),
    
    path('offer/', OfferListView.as_view()),
    path('offer/create/', OfferCreateView.as_view()),
    path('offer/<int:pk>/', OfferDetailView.as_view()),
    path('offer/<int:pk>/update/', OfferUpdateView.as_view()),
    
    path('test/', Test.as_view()),
    path('test2/', TestCreateOrderView.as_view()),
]

scaffolding/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

#To create initial migrations for an app, run makemigrations and specify the app name. The migrations folder will be created.
#./manage.py makemigrations <myapp>





class Technician(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    adress = models.CharField(max_length=200, null=True)
    zip_code = models.IntegerField(default=0, null=True)
    city = models.CharField(max_length=200, null=True)
    phone = models.IntegerField(default=0, null=True)
    email = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return self.title + " " + self.first_name

class Customer(models.Model):
    title = models.CharField(max_length=200, null=True, default="Entreprise", blank=True)
    name = models.CharField(max_length=200, null=True)
    adress = models.CharField(max_length=200, null=True, blank=True)
    zip_code = models.IntegerField(default=0, null=True)
    city = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    def __str__(self):
        return self.title + " " + self.name
    

    
class Offer(models.Model):
    STATUS = (
        ("Work in Progress", "Work in Progress"),
        ("Sended to Customer", "Sended to Customer"),
        ("Accepted", "Accepted"),
        ("Declined", "Declined"),
        )
    title = models.CharField(max_length=200, null=True)
    construction_site_name = models.CharField(max_length=200, null=True)
    construction_site_adress = models.CharField(max_length=200, null=True)
    construction_site_zip_code = models.IntegerField(default=0, null=True)
    construction_site_city = models.CharField(max_length=200, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    article = models.ManyToManyField("Article", through="Offer_article")
    def __str__(self):
        return str(self.customer)
    
class Category_Article(models.Model):
    title = models.CharField(max_length=200, null=True)
    num = models.IntegerField(default=100, null=True, blank=True)
    def __str__(self):
        return str(self.num) + " - " + self.title
    
class Article(models.Model):
    title = models.CharField(max_length=200, null=True)
    num = models.IntegerField(default=100, null=True, blank=True)
    prix_installation = models.FloatField(default=0, null=True, blank=True)
    date_installation = models.DateField(null=True, blank=True)
    prix_location = models.FloatField(default=0, null=True, blank=True)
    date_debut_location = models.DateField(null=True, blank=True)
    date_fin_location = models.DateField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    category_article = models.ForeignKey(Category_Article, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.num) + " - " +  self.title
    
class Offer_article(models.Model):
    offer =  models.ForeignKey(Offer, null=True, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True)

class Contact(models.Model):
    title = models.CharField(max_length=200, null=True)
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    adress = models.CharField(max_length=200, null=True)
    zip_code = models.IntegerField(default=0, null=True)
    city = models.CharField(max_length=200, null=True)
    phone = models.IntegerField(default=0, null=True)
    email = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return self.title + " " + self.first_name + " " + self.customer.title + " " + self.customer.name


"""


class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)
    quantity = models.FloatField(null=True)
    price = models.FloatField(null=True)
    def __str__(self):
        return self.name
    
    
class Article(models.Model):
    CATEGORY = (
        ("Echaudage de façade", "Echaudage de façade"),
        ("Supplément échafaudage de façade", "Supplément échafaudage de façade"),
        ("Echafaudage lourd", "Echafaudage lourd"),
        ("Travaux spéciaux", "Travaux spéciaux"),
        
        )
    name = models.CharField(max_length=200, null=True)
    price =  models.FloatField(null=True)
    category = models.CharField(max_length=200, null=True, choices=CATEGORY)
    description = models.TextField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    tags = models.ManyToManyField(Tag)#il faudrais une arborescence la dériere
    
    def __str__(self):
        return self.name
    
class Offer(models.Model):
    
    STATUS = (
        ("Work in Progress", "Work in Progress"),
        ("Sended to Customer", "Sended to Customer"),
        ("Accepted", "Accepted"),
        ("Declined", "Declined"),
        )
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)#lie notre offre a customer
    article = models.ManyToManyField(Article)#il faudrais une arborescence la dériere
    #article = models.ForeignKey(Article, null=True, on_delete=models.SET_NULL)#lie notre offre à un Article ***NUL***
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)#ok
    construction_site_name = models.CharField(max_length=200, null=True)
    
    def __str__(self):
        return self.customer.first_name + " " + self.customer.last_name + " " + self.construction_site_name
    

class Contact(models.Model):
    
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return self.first_name + " " + self.last_name
    
    class Installation(models.Model):
    title = models.CharField(max_length=200, null=True)
    qty = models.CharField(max_length=200, null=True, blank=True)
    unity = models.CharField(max_length=200, null=True, blank=True)
    price = models.CharField(max_length=200, null=True, blank=True)
    date_montage = models.DateField(blank=True)
    date_demontage = models.DateField(blank=True)
    
class Location(models.Model):
    title = models.CharField(max_length=200, null=True)
    qty = models.CharField(max_length=200, null=True, blank=True)
    unity = models.CharField(max_length=200, null=True, blank=True)
    price = models.CharField(max_length=200, null=True, blank=True)
    date_debut_location = models.DateField(blank=True)
    date_fin_location = models.DateField(blank=True)
"""
    
    

scaffolding/forms.py
#from django.forms import ModelForm
#from django.contrib.auth.forms import UserCreationForm
#from django.contrib.auth.models import User
from django import forms
from .models import Customer, Category_Article, Article, Offer, Offer_article
from django.forms import inlineformset_factory, formset_factory, modelformset_factory





"""
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
"""


    
class CustomerModelForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = (
            "title",
            "name",
            "adress",
            "zip_code",
            "city",
            "phone",
            "email",
            )
        

    
class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category_Article
        fields = (
            "title",
            "num",
            )
        
        

class ArticleModelForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = (
            "title",
            "num",
            )



class SimpleArticleModelForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = (
            "title",
            "num",
            "category_article"
            )
   
class OfferModelForm(forms.ModelForm):
    class Meta:
        model = Offer      
        fields = (
                "title",
                "construction_site_name",
                "construction_site_adress",
                "construction_site_zip_code",
                "construction_site_city",
                "status",
                "customer",
                "article",
            )



class ComplexeArticleModelForm(forms.ModelForm):
    class Meta:
        model = Article      
        fields = (
                "title",
                "num",
                "prix_installation",
                "date_installation",
                "prix_location",
                "date_debut_location",
                "date_fin_location",
            )

ArticleFormSet = inlineformset_factory(Article, Offer_article, fields=("title",), extra=3)

TestFormSet = formset_factory(Customer)

scaffolding/views.py
from django.shortcuts import render, redirect
#from django.http import HttpResponse
# Create your views here.
from django.contrib.auth.forms import UserCreationForm #, AuthenticationForm
#from .forms import CreateUserForm
#from django.contrib.auth import authenticate
from .models import Customer, Category_Article, Offer, Article, Offer_article
from .forms import CustomerModelForm, CategoryModelForm , ArticleModelForm, SimpleArticleModelForm, OfferModelForm, ComplexeArticleModelForm, ArticleFormSet, TestFormSet
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
#from django.forms.formsets import formset_factory
#from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from extra_views import ModelFormSetView, CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetFactory
#CRUD - CREATE - RETRIEVE - UPDATE - DELETE - LIST

class SignupView(CreateView):
    template_name = "registration/signup.html"
    form_class = UserCreationForm
    def get_success_url(self):
        return "/login"
    
class HomePageView(TemplateView):
    template_name = "scaffolding/home.html"
    
# CUSTOMER

class CustomerListView(ListView):
    template_name = "scaffolding/customer.html"
    queryset = Customer.objects.all().order_by("name")

class CustomerDetailView(DetailView):
    template_name = "scaffolding/customer_detail.html"
    queryset = Customer.objects.all()

class CustomerCreateView(CreateView):
    template_name = "scaffolding/customer_create.html"
    form_class = CustomerModelForm
    def get_success_url(self):
        return "/customer"

class CustomerUpdateView(UpdateView):
    template_name = "scaffolding/customer_update.html"
    form_class = CustomerModelForm
    queryset = Customer.objects.all()
    def get_success_url(self):
        return "/customer"

class CustomerDeleteView(DeleteView):
    template_name = "scaffolding/customer_delete.html"
    form_class = CustomerModelForm
    queryset = Customer.objects.all()
    def get_success_url(self):
        return "/customer"

# CATEGORY

class CategoryListView(ListView):
    template_name = "scaffolding/category.html"
    queryset = Category_Article.objects.all().order_by("title")

class CategoryDetailView(DetailView):
    template_name = "scaffolding/category_detail.html"
    queryset = Category_Article.objects.all()
    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        context['form'] = ArticleModelForm
        return context
    def post(self, request, **kwargs):
        form = ArticleModelForm()
        if request.method == "POST":
            form = ArticleModelForm(request.POST)
            if form.is_valid():
                art =  form.save(commit=False)
                art.category_article_id = self.kwargs['pk']
                art.save()
                return redirect("/category")
        context = {"form": form}
        return render(request, "scaffolding/home.html", context) #adress n'existe pas faut la changer

class CategoryCreateView(CreateView):
    template_name = "scaffolding/category_create.html"
    form_class = CategoryModelForm
    def get_success_url(self):
        return "/category"

class ArticleCreateView(CreateView):
    template_name = "scaffolding/article.html"
    form_class = SimpleArticleModelForm
    def get_success_url(self):
        return "/category"

# OFFER

class OfferListView(ListView):
    template_name = "scaffolding/offer.html"
    queryset = Offer.objects.all()

class OfferCreateView(CreateView):
    template_name = "scaffolding/offer_create.html"
    form_class = OfferModelForm
    def get_success_url(self):
        return "/offer"
    
class OfferDetailView(DetailView):
    model = Offer # = queryset = Offer.objects.all()
    template_name = "scaffolding/offer_detail.html"
    #context_object_name = 'list_offre'
    def get_context_data(self, **kwargs):
        context = super(OfferDetailView, self).get_context_data(**kwargs)
        context['test_list'] = Offer.article.through.objects.all().filter(offer_id=self.kwargs['pk'])
        context["test_list2"] = ArticleFormSet()
        return context

class OfferUpdateView(UpdateView):
    template_name = "scaffolding/offer_update.html"
    form_class = OfferModelForm
    queryset = Offer.objects.all()
    def get_context_data(self, **kwargs):
        context = super(OfferUpdateView, self).get_context_data(**kwargs)
        context['test_list'] = Offer.article.through.objects.all().filter(offer_id=self.kwargs['pk'])
        context["test_list2"] = ComplexeArticleModelForm
        return context
    def get_success_url(self):
        return "/offer"
    
class Test(ModelFormSetView):
    model = Customer
    fields="__all__"
    template_name = "scaffolding/test.html"

    def get_success_url(self):
        return "/customer"

class TestItemInline(InlineFormSetFactory):
    model = Offer_article
    fields="__all__"

class TestCreateOrderView(CreateWithInlinesView):
    model = Offer
    inlines = [TestItemInline]
    fields = "__all__"
    template_name = "scaffolding/test2.html"

scaffolding/templates/scaffolding/article.html
{% extends "base.html" %}


{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/input.css' %}">

 <form method="post" autocomplete="off" class="relative mb-4">
    {% csrf_token %}

    <p>{{ form }}</p>

    <button type="submit" class="my-5 border-2 border-green-600 rounded-lg px-3 py-2 text-green-400 cursor-pointer hover:bg-green-600 hover:text-green-200">Créer</button>
    </form>





{% endblock content %}

scaffolding/templates/scaffolding/category_create.html
{% extends "base.html" %}



{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/input.css' %}">

<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto flex sm:flex-nowrap flex-wrap">
    <div class="lg:w-2/3 md:w-1/2 bg-gray-300 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative">
      
    </div>
    <div class="lg:w-1/3 md:w-1/2 bg-white flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0">
      <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Categorie d'article</h2>
      
    <form method="post" autocomplete="off" class="relative mb-4">
    {% csrf_token %}
    {{form}}
    
    

    
    <button type="submit" class="my-5 border-2 border-purple-600 rounded-lg px-3 py-2 text-purple-400 cursor-pointer hover:bg-purple-600 hover:text-purple-200">Créer</button>
    </form>
      
    </div>
  </div>
</section>


   





{% endblock content %}

scaffolding/templates/scaffolding/category_detail.html
{% extends "base.html" %}



{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/input.css' %}">

<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto flex sm:flex-nowrap flex-wrap">
    <div class="lg:w-2/3 md:w-1/2 bg-gray-300 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative">
      
    </div>
    <div class="lg:w-1/3 md:w-1/2 bg-white flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0">
      <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">{{ category_article.num }} {{ category_article.title }}</h2>
    <form method="post" class="relative mb-4">



    
    {% for obj in category_article.article_set.all %}
    <p>{{obj}}</p> 
    {% endfor %}
    </form>
      
      

    </div>
  </div>
</section>



    <form method="post" autocomplete="off" class="relative mb-4">
    {% csrf_token %}

    <p>{{ form }}</p>

    <button type="submit" class="my-5 border-2 border-green-600 rounded-lg px-3 py-2 text-green-400 cursor-pointer hover:bg-green-600 hover:text-green-200">Créer</button>
    </form>
    
{% endblock content %}

scaffolding/templates/scaffolding/customer.html
{% extends "base.html" %}

{% block content %}
<div class="bg-gray-900">
  <div class="w-full">
    <div class="flex">
      <div class="m-auto my-1.5 flex flex-row gap-6">
        
        <!-- Orange Button -->
        <a href=/customer/create/ class="border-2 border-yellow-600 rounded-lg px-3 py-2 text-yellow-400 cursor-pointer hover:bg-yellow-600 hover:text-yellow-200">
          Créer un client
        </a>
        
           
      </div>
    </div>
  </div>
</div>




        
<table class="w-full table-auto border-separate">
  <thead>
    <tr>
      <th>Titre</th>
      <th>Name</th>
      <th>Adress</th>
      <th>NPA</th>
      <th>Ville</th>
    </tr>
  </thead>
  
          {% for customer in object_list %}
  <tbody>
    <tr class="hover:bg-yellow-600 hover:text-yellow-200">
      <td class="border border-yellow-600 rounded-lg px-2"><a style="display:inline-block;width:100%;height:100%;" href="/customer/{{customer.pk}}">{{customer.title}}</a></td>
      <td class="border border-yellow-600 rounded-lg px-2"><a style="display:inline-block;width:100%;height:100%;" href="/customer/{{customer.pk}}">{{customer.name}}</a></td>
      <td class="border border-yellow-600 rounded-lg px-2"><a style="display:inline-block;width:100%;height:100%;" href="/customer/{{customer.pk}}">{{customer.adress}}</a></td>
      <td class="border border-yellow-600 rounded-lg px-2"><a style="display:inline-block;width:100%;height:100%;" href="/customer/{{customer.pk}}">{{customer.zip_code}}</a></td>
      <td class="border border-yellow-600 rounded-lg px-2"><a style="display:inline-block;width:100%;height:100%;" href="/customer/{{customer.pk}}">{{customer.city}}</a></td>
    </tr>


  </tbody>

        

        {% endfor %}
</table>


{% endblock content %}

scaffolding/templates/scaffolding/customer_create.html
{% extends "base.html" %}



{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/input.css' %}">

<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-12">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Créer un nouveau client</h1>

    </div>
    <div class="lg:w-1/2 md:w-2/3 mx-auto">
      <div class="flex flex-wrap -m-2">
        <div class="p-2 w-full">
          <div class="relative">
          
<form method="post"  class="w-full py-4 bg-blue-300 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" autocomplete="off">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 my-4 focus:outline-none hover:bg-indigo-600 rounded text-lg">Créer un nouveau client</button>
</form>

           </div>
        </div>
        <div class="p-2 w-full">
          
        </div>
      </div>
    </div>
  </div>
</section>

      

      

   





{% endblock content %}

scaffolding/templates/scaffolding/customer_delete.html
{% extends "base.html" %}



{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/input.css' %}">

<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto flex sm:flex-nowrap flex-wrap">
    <div class="lg:w-2/3 md:w-1/2 bg-gray-300 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative">
      
    </div>
    <div class="lg:w-1/3 md:w-1/2 bg-white flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0">
      <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">DELETE</h2>
      
    <form method="post" class="relative mb-4">
    {% csrf_token %}
    {{form}}
    
    
    <p>Etes vous sur de vouloir supprimer {{customer.name}} ? </p>
    
    <button type="submit" class="my-5 border-2 border-purple-600 rounded-lg px-3 py-2 text-purple-400 cursor-pointer hover:bg-purple-600 hover:text-purple-200">Supprimer {{customer.name}}</button>
    </form>
      
    </div>
  </div>
</section>


   





{% endblock content %}

scaffolding/templates/scaffolding/customer_detail.html
{% extends "base.html" %}



{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/input.css' %}">

<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto flex sm:flex-nowrap flex-wrap">
    <div class="lg:w-2/3 md:w-1/2 bg-gray-300 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative">
      
    </div>
    <div class="lg:w-1/3 md:w-1/2 bg-white flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0">
      <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Coordonnées</h2>
      
    <form method="post" class="relative mb-4">

    <p>{{ customer.title }}</p> 
    <p>{{ customer.name }}</p> 
    <p>{{ customer.adress }}</p>
    <p>{{ customer.zip_code }}</p>
    <p>{{ customer.city }}</p>
    <p>{{ customer.phone }}</p>
    <p>{{ customer.email }}</p>
    </form>
      
        <a href="/customer/{{customer.pk}}/update/" class="border-2 border-yellow-600 rounded-lg px-3 py-2 text-yellow-400 cursor-pointer hover:bg-yellow-600 hover:text-yellow-200">
          Modifier
        </a>  
        
        <a href="/customer/{{customer.pk}}/delete/" class="border-2 border-red-600 rounded-lg px-3 py-2 text-red-400 cursor-pointer hover:bg-red-600 hover:text-red-200">
          Suprimmer
        </a>  
    </div>
  </div>
</section>


   
    
    
    
{% endblock content %}

scaffolding/templates/scaffolding/customer_update.html
{% extends "base.html" %}



{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/input.css' %}">

<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto flex sm:flex-nowrap flex-wrap">
    <div class="lg:w-2/3 md:w-1/2 bg-gray-300 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative">
      
    </div>
    <div class="lg:w-1/3 md:w-1/2 bg-white flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0">
      <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">UPDATE</h2>
      
    <form method="post" autocomplete="off" class="relative mb-4">
    {% csrf_token %}
    {{form}}
    
    

    
    <button type="submit" class="my-5 border-2 border-purple-600 rounded-lg px-3 py-2 text-purple-400 cursor-pointer hover:bg-purple-600 hover:text-purple-200">Mettre à jour</button>
    </form>
      
    </div>
  </div>
</section>


   





{% endblock content %}

scaffolding/templates/scaffolding/home.html
{% extends "base.html" %}

{% block content %}
<div class="bg-gray-900">
  <div class="w-full h-screen">
    <div class="flex h-screen">
      <div class="m-auto flex flex-col gap-6 items-center">
        
        <!-- Orange Button -->
        <a href="/customer" class="border-2 border-yellow-600 rounded-lg px-3 py-2 text-yellow-400 cursor-pointer hover:bg-yellow-600 hover:text-yellow-200">
          Clients
        </a>
        
        <!-- Orange Button -->
        <a href="/offer" class="border-2 border-blue-600 rounded-lg px-3 py-2 text-blue-400 cursor-pointer hover:bg-blue-600 hover:text-blue-200">
          Offres
        </a>
        
        <!-- Green Button -->
        <div class="border-2 border-green-600 rounded-lg px-3 py-2 text-green-400 cursor-pointer hover:bg-green-600 hover:text-green-200">
          Factures
        </div>
        
        <!-- Purple Button -->
        <a href="/category" class="border-2 border-purple-600 rounded-lg px-3 py-2 text-purple-400 cursor-pointer hover:bg-purple-600 hover:text-purple-200">
          Articles CAN
        </a>

      </div>
    </div>
  </div>
</div>
{% endblock content %}

scaffolding/templates/scaffolding/test.html
{% extends "base.html" %}



{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/test.css' %}">

<h1> TEST ZONE</h1>
    
    



    
    
    
    









  

<form method="post" autocomplete="off" class="relative mb-4">

{% csrf_token %}
{{ formset.management_form }}
{% for form in formset %}

<div class="border border-yellow-600 rounded-lg px-2">
{% for field in form %}
{{field}}
{% endfor %}
</div>



{% endfor %}
<button type="submit" class="my-5 border-2 border-green-600 rounded-lg px-3 py-2 text-green-400 cursor-pointer hover:bg-green-600 hover:text-green-200">Mettre a jour</button>
</form> 





  

   


{% endblock content %}